src/config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  #sidekiq
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
  end

  # action cable
  mount ActionCable.server => '/cable'

  root 'timelines#index'
  
  # discovery
  get 'discovery' => 'discovery#index'

  # dashboard
  get 'dashboard' => 'dashboard#index'

  # timeline
  get 'tl' => 'timelines#tl'
  get 'tl/follow' => 'timelines#follow'
  get 'tl/current' => 'timelines#current'
  get 'tl/group/:group_aid' => 'timelines#group'

  # account
  get '@:name_id' => 'accounts#show', as: 'account', constraints: { name_id: /[A-Za-z0-9\-_\.@]*/ }
  get '@:name_id/icon' => 'accounts#show_icon', as: 'show_icon', constraints: { name_id: /.*/ }
  get '@:name_id/banner' => 'accounts#show_banner', as: 'show_banner', constraints: { name_id: /.*/ }
  post '@:name_id/follow' => 'accounts#follow', as: 'follow', constraints: { name_id: /.*/ }
  patch '@:name_id/upate' => 'accounts#update', as: 'update_account'

  # item
  get 'items' => 'items#index'
  get 'items/new' => 'items#new', as: 'new_item'
  post 'items/create' => 'items#create', as: 'create_item'
  get 'items/:aid' => 'items#show', as: 'item'
  get 'items/:aid/edit' => 'items#edit', as: 'edit_item'
  patch 'items/:aid/update' => 'items#update', as: 'update_item'
  delete 'items/:aid/destroy' => 'items#destroy', as: 'destroy_item'

  # reaction
  post 'react/:item_id/:emoji_id' => 'reactions#react', as: 'react'

  # storage
  get 'storage' => 'storage#index'

  # image
  resources :images, param: :aid, only: %i[ show create update delete ]
  get 'images/:aid/icon' => 'images#show_icon'
  get 'images/:aid/banner' => 'images#show_banner'

  # video
  resources :videos, param: :aid, only: %i[ create update delete ]

  # notifications
  #resources :videos, param: :aid, only: %i[ create update delete ]
  get 'notifications' => 'notifications#index'
  get 'notifications/new' => 'notifications#new', as: 'new_notification'
  post 'notifications/create' => 'notifications#create', as: 'create_notification'

  # message
  get 'messages' => 'messages#index'
  get 'messages/:group_aid' => 'messages#show', as: 'message'
  post 'message/:group_aid/create' => 'messages#create', as: 'create_message'

  # group
  get 'groups' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/create' => 'groups#create', as: 'create_group'
  get 'groups/:aid' => 'groups#show', as: 'group'
  post 'groups/:group_aid/add/:account_aid' => 'groups#group_add', as: 'group_add'
  post 'groups/:group_aid/remove/:account_aid' => 'groups#group_remove', as: 'group_remove'

  # emoji
  get 'emojis' => 'emojis#index'
  get 'emojis/new' => 'emojis#new', as: 'new_emoji'
  post 'emojis/create' => 'emojis#create', as: 'create_emoji'
  get 'emojis/:aid' => 'emojis#show', as: 'emoji'
  get 'emojis/:aid/edit' => 'emojis#edit', as: 'edit_emoji'
  patch 'emojis/:aid/update' => 'emojis#update', as: 'update_emoji'
  delete 'emojis/:aid/destroy' => 'emojis#destroy', as: 'destroy_emoji'

  # tag
  get 'tags' => 'tags#index'
  get 'tags/new' => 'tags#new', as: 'new_tag'
  post 'tags/create' => 'tags#create', as: 'create_tag'
  get 'tags/:aid' => 'tags#show', as: 'tag'
  get 'tags/:aid/edit' => 'tags#edit', as: 'edit_tag'
  patch 'tags/:aid/update' => 'tags#update', as: 'update_tag'
  delete 'tags/:aid/destroy' => 'tags#destroy', as: 'destroy_tag'

  # list

  # wallet

  # a_shop

  # product

  # map

  # world

  # application

  # subscription

  # signup
  get 'signup' => 'signup#index'
  get 'signup/check' => 'signup#check'
  post 'signup/entry' => 'signup#entry'
  post 'signup/create' => 'signup#create'

  # session
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#logout'

  # setting
  get 'settings' => 'settings#index'
  get 'settings/profile' => 'settings#profile'
  get 'settings/account' => 'settings#account'
  get 'settings/storage' => 'settings#storage'
  get 'settings/contents' => 'settings#contents'
  get 'settings/activity' => 'settings#activity'
  get 'settings/notifications' => 'settings#notifications'
  get 'settings/display' => 'settings#display'
  get 'settings/security_and_authority' => 'settings#security_and_authority'
  get 'settings/analytics' => 'settings#analytics'
  get 'settings/bills_and_payments' => 'settings#bills_and_payments'
  get 'settings/others' => 'settings#others'

  # resource
  get 'resources' => 'resources#index'
  get 'about' => 'resources#about'
  get 'info' => 'resources#info'
  get 'help' => 'resources#help'
  get 'privacy_policy' => 'resources#privacy_policy'
  get 'disclaimer' => 'resources#disclaimer'
  get 'page1' => 'resources#page1'
  get 'sitemap' => 'resources#sitemap'
  get 'tos' => 'resources#tos'
  get 'feedback' => 'resources#feedback'
  get 'help' => 'resources#help'
  get 'release_notes' => 'resources#release_notes'
  get 'blog' => 'resources#blog'

  # administorator
  namespace :admin do

    # dashboard
    root 'dashboard#index'

    # account
    resources :accounts, param: :aid, constraints: { name_id: /.*/ }, except: %i[ show ]

    # session
    resources :sessions, param: :uuid, except: %i[ show ]

    # invitation
    resources :invitations, param: :uuid, except: %i[ show ]

    # item
    get 'items' => 'items#index', as: 'items'

    # test
    get 'test' => 'test#index'
    get 'test/explore' => 'test#explore'
    get 'test/explore/:id' => 'test#show', constraints: { id: /.*/ }
    get 'test/new'
    post 'test/generate'
    post 'test/verify'
    post 'test/digest'
  end

  # api v1
  namespace :v1 do

    # app_status
    root 'resources#index'

    # session
    post 'sessions/new' => 'sessions#new'
    post 'sessions/check' => 'sessions#check'
    post 'login' => 'sessions#login'
    delete 'logout' => 'sessions#logout'

    # timeline
    post 'tl' => 'timelines#index'
    post 'tl/follow' => 'timelines#follow'#
    post 'tl/current' => 'timelines#current'#
    post 'tl/group/:group_aid' => 'timelines#group'#

    # account
    post '@:name_id' => 'accounts#show', as: 'account'
    post '@:name_id/followers' => 'accounts#followers', as: 'followers'
    post '@:name_id/following' => 'accounts#following', as: 'following'

    # signup
    post 'signup/check' => 'signup#check'
    post 'signup/create' => 'signup#create'

    # item
    post 'items' => 'items#index', as: 'items'
    post 'items/create' => 'items#create', as: 'create_items'
    post 'items/:item_id' => 'items#show', as: 'item'

    # activity pub
    post 'activitypub/inbox' => 'activity_pub#inbox'
  end

  # activity pub
  namespace :ap do
    # account
    get '@:name_id' => 'accounts#show', as: 'account'
    post '@:name_id/inbox' => 'accounts#inbox', as: 'account_inbox'
    get '@:name_id/outbox' => 'accounts#outbox', as: 'account_outbox'
    get '@:name_id/followers' => 'accounts#followers', as: 'account_followers'
    get '@:name_id/following' => 'accounts#following', as: 'account_following'
  end

  # .well-known
  get '/.well-known/host-meta' => 'well_known#host_meta'
  get '/.well-known/webfinger' => 'well_known#webfinger'

end

src/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  include ActivityPub
  before_action :set_account, except: %i[ show ]
  before_action :logged_in_account, except: %i[ show ]

  def show
    @account = find_account_by_nid(params[:name_id])
  end
  def follow
    account = find_account_by_nid(params[:name_id])
    this_follow_params = {
      followed: account,
      follower: @current_account
    }
    if account.outsider
      if Follow.exists?(this_follow_params)
        follow = Follow.find_by(this_follow_params)
        undo_follow(follow_to: account, follow_from: @current_account, uid: follow.uid)
        follow.delete
        flash[:success] = 'フォロー取り消し依頼しました'
      else
        this_follow_params.merge!({uid: SecureRandom.uuid})
        Rails.logger.info(this_follow_params[:uid])
        follow = Follow.new(this_follow_params)
        if follow.save!
          ap_follow(follow_to: account, follow_from: @current_account, uid: this_follow_params[:uid])
          flash[:success] = 'フォロー依頼しました'
        else
          flash[:danger] = 'フォロー依頼できません'
        end
      end
    else
      if Follow.exists?(this_follow_params)
        Follow.where(this_follow_params).delete_all
        flash[:success] = 'フォローを取り消しました'
      else
        this_follow_params.merge!({accepted: true})
        follow = Follow.new(this_follow_params)
        if follow.save!
          flash[:success] = 'フォローしました'
        else
          flash[:danger] = '失敗しました'
        end
      end
    end
    redirect_to root_path
  end
  def update
    @account = @current_account
    if @account.update(account_update_params)
      treat_image(@account.icon_id, 'icon') if @account.icon_id.present? # 更新されたときのみ実行が好ましい
      treat_image(@account.banner_id, 'banner') if @account.banner_id.present? # 更新されたときのみ実行が好ましい
      flash[:success] = "更新しました"
      redirect_to account_path(@account.name_id)
    else
      flash[:danger] = "更新できませんでした#{@account.errors.full_messages.join(", ")}"
      redirect_to settings_account_path
    end
  end
  def password_update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "更新しました"
      redirect_to user_path(@user.user_id)
    else
      flash[:danger] = "更新できませんでした"
      redirect_to settings_account_path
    end
  end
  def destroy
  end
  private
  def set_account
    @account = Account.find_by(name_id: params[:name_id])
  end
  def account_params
    params.require(:account).permit(
      :name,
      :name_id,
      :icon_id,
      :banner_id,
      :summary,
      :location,
      :birthday,
      :password,
      :password_confirmation
    )
  end
  def account_update_params
    params.require(:account).permit(
      :name,
      :name_id,
      :icon_id,
      :banner_id,
      :summary,
      :location,
      :birthday
    )
  end
  def account_password_update_params
    params.require(:account).permit(
      :password,
      :password_confirmation
    )
  end
end

src/app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::ApplicationController
  before_action :set_account, except: %i[ index ]

  def index
    @accounts = Account.all
  end
  def new
  end
  def create
  end
  def edit
  end
  def update
    if @account.update(account_update_params)
      flash[:success] = '変更しました'
      redirect_to admin_accounts_path
    else
      flash.now[:danger] = "変更できませんでした"
      render 'edit'
    end
  end
  def destroy
    if @account.update(deleted: true)
      flash[:success] = '変更しました'
      redirect_to admin_accounts_path
    else
      flash.now[:danger] = "変更できませんでした"
      redirect_to admin_accounts_path
    end
  end
  private
  def set_account
    @account = Account.find_by(aid: params[:aid])
  end
  def account_update_params
    params.require(:account).permit(
      :name, :name_id, :bio, :location, :birthday,
      :authenticated, :public_visibility, :role, :activated,
      :sensitive, :explorable,
      :locked, :silenced, :suspended, :frozen, :deleted
    )
  end
end

src/app/controllers/ap/accounts_controller.rb
class Ap::AccountsController < Ap::ApplicationController
  before_action :set_account, only: %i[ show inbox outbox followers following ]
  def show
    render json: {
      "@context": "https://www.w3.org/ns/activitystreams",
      type: "Person",
      id: full_api_url("@#{@account.name_id}"),
      url: full_api_url("@#{@account.name_id}"),
      tag: [],
      published: @account.created_at,
      discoverable: true,
      attachment: [],
      manuallyApprovesFollowers: true,
      name: @account.name,
      summary: "",
      icon: {
        type: 'Image',
        mediaType: 'image/webp',
        url: image_url(@account.icon_id, 'icon')
      },
      preferredUsername: @account.name_id,
      inbox: full_api_url("ap/@#{@account.name_id}/inbox"),
      outbox: full_api_url("ap/@#{@account.name_id}/outbox"),
      followers: full_api_url("ap/@#{@account.name_id}/followers"),
      following: full_api_url("ap/@#{@account.name_id}/following")
    }
  end
  def inbox
    render json: {
      "@context": "https://www.w3.org/ns/activitystreams",
      type: "OrderedCollection",
      id: full_api_url("ap/@#{@account.name_id}/inbox"),
      items: []
    }
  end
  def outbox
    render json: {
      "@context": "https://www.w3.org/ns/activitystreams",
      type: "OrderedCollection",
      id: full_api_url("ap/@#{@account.name_id}/outbox"),
      items: []
    }
  end
  def followers
    render json: {
      "@context": "https://www.w3.org/ns/activitystreams",
      type: "Collection",
      id: full_api_url("ap/@#{@account.name_id}/followers"),
      items: [],
      totalItems: 1
    }
  end
  def following
    render json: {
      "@context": "https://www.w3.org/ns/activitystreams",
      type: "Collection",
      id: full_api_url("ap/@#{@account.name_id}/following"),
      items: [],
      totalItems: 1
    }
  end
  private
  def set_account
    @account = Account.find_by(
      name_id: params[:name_id],
      activated: true,
      locked: false,
      silenced: false,
      suspended: false,
      frozen: false,
      deleted: false
    )
  end
end

src/app/controllers/v1/accounts_controller.rb
class V1::AccountsController < V1::ApplicationController
  before_action :set_account, only: %i[ show followers following ]
  def show
    render json: account_data(@account)
  end
  def show_old
    render json: {
      name_id: @account.name_id,
      name: @account.name,
      icon_url: generate_ati_url(@account.account_id, 'icon', @account.icon_id),
      banner_url: generate_ati_url(@account.account_id, 'banner', @account.banner_id),
      bio: @account.bio,
      location: @account.location,
      birthday: @account.birthday,
      followers: @account.followers.count,
      following: @account.following.count,
      items_count: @account.items_count,
      created_at: @account.created_at,
      updated_at: @account.updated_at,
      public_key: @account.public_key,
      items: @account.items.map {|item| {
        item_id: item.item_id,
        item_type: item.item_type,
        meta: item.meta,
        content: item.content,
        sensitive: item.sensitive,
        version: item.version,
        created_at: item.created_at,
        updated_at: item.updated_at,
        reactions: item.reactions.group(:reaction_id).count.map { |key, value| {
          reaction_id: key,
          content: item.reactions.find_by(reaction_id: key).content,
          count: value
        }},
        images: item.images.map {|image| {
          image_id: image.image_id,
          name: image.name,
          description: image.description,
          url: generate_ati_url(image.account.account_id, 'images', image.image_id)
        }}
      }}
    }
  end
  def followers
    render json: {
      name_id: @account.name_id,
      count: @account.followers.count,
      followers: @account.followers.map {|follower| {
        name: follower.name,
        name_id: follower.name_id,
        activitypub_id: follower.activitypub_id,
        icon_url: generate_ati_url(follower.account_id, 'icon', follower.icon_id),
        banner_url: generate_ati_url(follower.account_id, 'banner', follower.banner_id),
        bio: follower.bio,
        created_at: follower.created_at,
        updated_at: follower.updated_at,
      }}
    }
  end
  def following
    render json: {
      name_id: @account.name_id,
      count: @account.following.count,
      following: @account.following.map {|following| {
        name: following.name,
        name_id: following.name_id,
        activitypub_id: following.activitypub_id,
        icon_url: generate_ati_url(following.account_id, 'icon', following.icon_id),
        banner_url: generate_ati_url(following.account_id, 'banner', following.banner_id),
        bio: following.bio,
        created_at: following.created_at,
        updated_at: following.updated_at,
      }}
    }
  end
  def update
    pre_icon_id = @account.icon_id
    pre_banner_id = @account.banner_id
    if @account.update(account_update_params)
      generate_varinat_image(params[:account][:icon_id], pre_icon_id, 'icon')
      generate_varinat_image(params[:account][:banner_id], pre_banner_id, 'banner')
      flash[:success] = "更新成功!"
      redirect_to account_path(@account.name_id)
    else
      flash.now[:danger] = "更新できませんでした。"
      render 'edit'
    end
  end
  private
  def set_account
    @account = find_account_by_nid(params[:name_id])
  end
  def account_params
    params.require(:account).permit(
      :name,
      :name_id,
      :icon_id,
      :banner_id,
      :bio,
      :location,
      :birthday,
      :password,
      :password_confirmation
    )
  end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
  def add_roles
  end
end

src/app/views/accounts/_form.html.erb
<%= form_with model: @account, url: yield(:url), data: { turbo: false } do |f| %>
  <%= render 'shared/error_messages', instead: @account %>
  <% type = yield(:type) %>
  <div class="text-field-group">
    <%= f.text_field :icon_id, class: 'text-field-field', placeholder: ' ' %>
    <%= f.label :icon_id, 'アイコンID', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :banner_id, class: 'text-field-field', placeholder: ' ' %>
    <%= f.label :banner_id, 'バナーID', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :name, class: 'text-field-field', placeholder: ' ' %>
    <%= f.label :name, '名前', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :name_id, class: 'text-field-field', placeholder: ' ' %>
    <%= f.label :name_id, 'ID', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :bio, class: 'text-field-field', placeholder: ' ' %>
    <%= f.label :bio, '紹介', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :location, class: 'text-field-field', placeholder: ' ' %>
    <%= f.label :location, '場所', class: 'text-field-label' %>
  </div>
  <br/>
  <%= f.label :birthday, '誕生日' %>
  <%= f.datetime_field :birthday %>
  <br/>
  <% if type == 'pwedit' || type == 'new' %>
    <div class="text-field-group">
      <%= f.password_field :password, class: 'text-field-field', placeholder: ' ' %>
      <%= f.label :password, 'パスワード', class: 'text-field-label' %>
    </div>
    <br/>
    <div class="text-field-group">
      <%= f.password_field :password_confirmation, class: 'text-field-field', placeholder: ' ' %>
      <%= f.label :password_confirmation, 'パスワード確認', class: 'text-field-label' %>
    </div>
  <% elsif type == 'edit' %>
    <%= link_to 'パスワードを変更', password_edit_account_path %>
  <% end %>
  <br/>
  <%= f.submit yield(:submit_button_text) %>
<% end %>

src/app/views/accounts/show.html.erb
<% provide(:layout_type, 'default') %>

<% if @account.present? %>
  <% provide(:title, @account.name) %>

  <div class="account-container" id="account-container">
    <div class="top-container">
      <div class="banner-container" id="banner-container" >
        <% if !@account.banner_id.blank? %>
          <%= image_tag image_url(@account.banner_id, 'banner'), class: 'account-banner' %>
        <% else %>
          <%= image_tag 'banner.webp', class: 'account-banner' %>
        <% end %>
      </div>
    </div>
    <div class="name-container fixed" id="name-container">
      <div id="name-before"></div>
      <div class="icon-container">
        <% if !@account.icon_id.blank? %>
          <%= image_tag image_url(@account.icon_id, 'icon',), class: 'account-icon' %>
        <% else %>
          <%= image_tag 'icon.webp', class: 'account-icon' %>
        <% end %>
      </div>
      <div class="meta-container">
        <h1><%= @account.name %></h1>
        <div>@<%= @account.name_id %></div>
        <% if @account == @current_account %>
          <%= link_to('設定', settings_path) %>
        <% elsif @current_account.present? %>
          <% if Follow.exists?(followed: @account, follower: @current_account) %>
            <%= button_to("フォロー解除", follow_path(@account.name_id), method: :post) %>
          <% else %>
            <%= button_to("フォローする", follow_path(@account.name_id), method: :post) %>
          <% end %>
        <% else %>
          <%= button_to('ログインしてフォロー', login_path, method: :get) %>
        <% end %>
      </div>
    </div>

    <div class="profile-container">
      <div><span>紹介文:</span><%= @account.summary %></div>
      <div><span>場所:</span><%= @account.location %></div>
      <div><span>誕生日:</span><%= @account.birthday&.strftime("%Y年 %m月 %d日") %></div>
      <div><span>フォロワー:</span><%= @account.followers.count %></div>
      <div><span>フォロー中:</span><%= @account.following.count %></div>
      <div><span>投稿数:</span><%= @account.items.count %></div>
      <div><span>参加日:</span><%= @account.created_at.strftime("%Y年 %m月 %d日") %></div>
    </div>
    <div class="account-tab-container">
      <div>投稿</div>
      <div>返信</div>
      <div>メディア</div>
      <div>リアクション</div>
    </div>
    <div class="content-container">
      <div id="items">
        <% @account.items.each do |item| %>
          <% if item.replying.empty? %>
            <%= render 'items/item', item: item, show_reply_from: true %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <% provide(:title, '不明なアカウント') %>
  <p>@<%= params[:name_id] %>というアカウントが見つかりませんでした。。。</p>
<% end %>