src/config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  #sidekiq
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
  end

  # action cable
  mount ActionCable.server => '/cable'

  root 'timelines#index'
  
  # discovery
  get 'discovery' => 'discovery#index'

  # dashboard
  get 'dashboard' => 'dashboard#index'

  # timeline
  get 'tl' => 'timelines#tl'
  get 'tl/follow' => 'timelines#follow'
  get 'tl/current' => 'timelines#current'
  get 'tl/group/:group_aid' => 'timelines#group'

  # account
  get '@:name_id' => 'accounts#show', as: 'account', constraints: { name_id: /[A-Za-z0-9\-_\.@]*/ }
  get '@:name_id/icon' => 'accounts#show_icon', as: 'show_icon', constraints: { name_id: /.*/ }
  get '@:name_id/banner' => 'accounts#show_banner', as: 'show_banner', constraints: { name_id: /.*/ }
  post '@:name_id/follow' => 'accounts#follow', as: 'follow', constraints: { name_id: /.*/ }
  patch '@:name_id/upate' => 'accounts#update', as: 'update_account'

  # item
  get 'items' => 'items#index'
  get 'items/new' => 'items#new', as: 'new_item'
  post 'items/create' => 'items#create', as: 'create_item'
  get 'items/:aid' => 'items#show', as: 'item'
  get 'items/:aid/edit' => 'items#edit', as: 'edit_item'
  patch 'items/:aid/update' => 'items#update', as: 'update_item'
  delete 'items/:aid/destroy' => 'items#destroy', as: 'destroy_item'

  # reaction
  post 'react/:item_id/:emoji_id' => 'reactions#react', as: 'react'

  # storage
  get 'storage' => 'storage#index'

  # image
  resources :images, param: :aid, only: %i[ show create update delete ]
  get 'images/:aid/icon' => 'images#show_icon'
  get 'images/:aid/banner' => 'images#show_banner'

  # video
  resources :videos, param: :aid, only: %i[ create update delete ]

  # notifications
  #resources :videos, param: :aid, only: %i[ create update delete ]
  get 'notifications' => 'notifications#index'
  get 'notifications/new' => 'notifications#new', as: 'new_notification'
  post 'notifications/create' => 'notifications#create', as: 'create_notification'

  # message
  get 'messages' => 'messages#index'
  get 'messages/:group_aid' => 'messages#show', as: 'message'
  post 'message/:group_aid/create' => 'messages#create', as: 'create_message'

  # group
  get 'groups' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/create' => 'groups#create', as: 'create_group'
  get 'groups/:aid' => 'groups#show', as: 'group'
  post 'groups/:group_aid/add/:account_aid' => 'groups#group_add', as: 'group_add'
  post 'groups/:group_aid/remove/:account_aid' => 'groups#group_remove', as: 'group_remove'

  # emoji
  get 'emojis' => 'emojis#index'
  get 'emojis/new' => 'emojis#new', as: 'new_emoji'
  post 'emojis/create' => 'emojis#create', as: 'create_emoji'
  get 'emojis/:aid' => 'emojis#show', as: 'emoji'
  get 'emojis/:aid/edit' => 'emojis#edit', as: 'edit_emoji'
  patch 'emojis/:aid/update' => 'emojis#update', as: 'update_emoji'
  delete 'emojis/:aid/destroy' => 'emojis#destroy', as: 'destroy_emoji'

  # tag
  get 'tags' => 'tags#index'
  get 'tags/new' => 'tags#new', as: 'new_tag'
  post 'tags/create' => 'tags#create', as: 'create_tag'
  get 'tags/:aid' => 'tags#show', as: 'tag'
  get 'tags/:aid/edit' => 'tags#edit', as: 'edit_tag'
  patch 'tags/:aid/update' => 'tags#update', as: 'update_tag'
  delete 'tags/:aid/destroy' => 'tags#destroy', as: 'destroy_tag'

  # list

  # wallet

  # a_shop

  # product

  # map

  # world

  # application

  # subscription

  # signup
  get 'signup' => 'signup#index'
  get 'signup/check' => 'signup#check'
  post 'signup/entry' => 'signup#entry'
  post 'signup/create' => 'signup#create'

  # session
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#logout'

  # setting
  get 'settings' => 'settings#index'
  get 'settings/profile' => 'settings#profile'
  get 'settings/account' => 'settings#account'
  get 'settings/storage' => 'settings#storage'
  get 'settings/contents' => 'settings#contents'
  get 'settings/activity' => 'settings#activity'
  get 'settings/notifications' => 'settings#notifications'
  get 'settings/display' => 'settings#display'
  get 'settings/security_and_authority' => 'settings#security_and_authority'
  get 'settings/analytics' => 'settings#analytics'
  get 'settings/bills_and_payments' => 'settings#bills_and_payments'
  get 'settings/others' => 'settings#others'

  # resource
  get 'resources' => 'resources#index'
  get 'about' => 'resources#about'
  get 'info' => 'resources#info'
  get 'help' => 'resources#help'
  get 'privacy_policy' => 'resources#privacy_policy'
  get 'disclaimer' => 'resources#disclaimer'
  get 'page1' => 'resources#page1'
  get 'sitemap' => 'resources#sitemap'
  get 'tos' => 'resources#tos'
  get 'feedback' => 'resources#feedback'
  get 'help' => 'resources#help'
  get 'release_notes' => 'resources#release_notes'
  get 'blog' => 'resources#blog'

  # administorator
  namespace :admin do

    # dashboard
    root 'dashboard#index'

    # account
    resources :accounts, param: :aid, constraints: { name_id: /.*/ }, except: %i[ show ]

    # session
    resources :sessions, param: :uuid, except: %i[ show ]

    # invitation
    resources :invitations, param: :uuid, except: %i[ show ]

    # item
    get 'items' => 'items#index', as: 'items'

    # test
    get 'test' => 'test#index'
    get 'test/explore' => 'test#explore'
    get 'test/explore/:id' => 'test#show', constraints: { id: /.*/ }
    get 'test/new'
    post 'test/generate'
    post 'test/verify'
    post 'test/digest'
  end

  # api v1
  namespace :v1 do

    # app_status
    root 'resources#index'

    # session
    post 'sessions/new' => 'sessions#new'
    post 'sessions/check' => 'sessions#check'
    post 'login' => 'sessions#login'
    delete 'logout' => 'sessions#logout'

    # timeline
    post 'tl' => 'timelines#index'
    post 'tl/follow' => 'timelines#follow'#
    post 'tl/current' => 'timelines#current'#
    post 'tl/group/:group_aid' => 'timelines#group'#

    # account
    post '@:name_id' => 'accounts#show', as: 'account'
    post '@:name_id/followers' => 'accounts#followers', as: 'followers'
    post '@:name_id/following' => 'accounts#following', as: 'following'

    # signup
    post 'signup/check' => 'signup#check'
    post 'signup/create' => 'signup#create'

    # item
    post 'items' => 'items#index', as: 'items'
    post 'items/create' => 'items#create', as: 'create_items'
    post 'items/:item_id' => 'items#show', as: 'item'

    # activity pub
    post 'activitypub/inbox' => 'activity_pub#inbox'
  end

  # activity pub
  namespace :ap do
    # account
    get '@:name_id' => 'accounts#show', as: 'account'
    post '@:name_id/inbox' => 'accounts#inbox', as: 'account_inbox'
    get '@:name_id/outbox' => 'accounts#outbox', as: 'account_outbox'
    get '@:name_id/followers' => 'accounts#followers', as: 'account_followers'
    get '@:name_id/following' => 'accounts#following', as: 'account_following'
  end

  # .well-known
  get '/.well-known/host-meta' => 'well_known#host_meta'
  get '/.well-known/webfinger' => 'well_known#webfinger'

end

src/app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :account
end

src/app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < Admin::ApplicationController
  def index
    @invitations = Invitation.all
  end
  def show
    @invitation = Invitation.find_by(invitation_code: params[:invitation_code])
  end
  def new
    @invitation = Invitation.new
  end
  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.account_id = @current_account.id
    if @invitation.save
      flash[:success] = "招待を作成しました。"
      redirect_to root_path
    else
      render 'new'
    end
  end
  def edit
    @invitation = Invitation.find_by(invitation_code: params[:invitation_code])
  end
  def update
    @invitation = Invitation.find_by(invitation_code: params[:invitation_code])
    if @invitation.update(invitation_update_params)
      flash[:success] = '変更しました。'
      redirect_to admin_invitation_path(@invitation.invitation_code)
    else
      flash.now[:danger] = "更新できませんでした。"
      render 'edit'
    end
  end
  def destroy
    # 本当に消す？
  end
  private
  def invitation_params
    params.require(:invitation).permit(:name, :invitation_code, :max_uses, :expires_at)
  end
  def invitation_update_params
    params.permit(:account_id, :name, :invitation_code, :uses, :max_uses, :expires_at, :deleted)
  end
end

src/app/controllers/api/invitations_controller.rb
class Api::InvitationsController < Api::ApplicationController
  before_action :set_item, only: %i[ show ]
  def index
    @items = Item.all
    render json: @items
  end
  def show
  end
  private
  def set_item
    @item = Item.find(params[:id])
  end
end

src/app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :logged_in_account
  before_action :set_invitation, only: %i[ show ]
  def index
    @invitations = Invitation.all
      .where(deleted: false)
  end

  def show
    @invitation = Invitation.find_by(code: params[:code])
  end

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.account_id = @current_account.id
    @invitation.uuid = SecureRandom.uuid
    if @invitation.save
      flash[:success] = "招待を作成しました。"
      redirect_to root_path
    else
      render 'new'
    end
  end
  def edit
    @invitation = Invitation.find_by(code: params[:code])
  end
  def update
  end
  def delete
    @invitation = Invitation.find_by(code: params[:code])
    @invitation.update(deleted: true)
  end
  private
  def set_invitation
    @invitation = Invitation
      .find_by(code: params[:code])
      .where(deleted: false)
  end
  def invitation_params
    params.require(:invitation).permit(
      :name,
      :code,
      :max_uses,
      :expires_at
    )
  end
end

src/app/controllers/v1/invitations_controller.rb
class V1::InvitationsController < V1::ApplicationController
  before_action :set_item, only: %i[ show ]
  def index
    @items = Item.all
    render json: @items
  end
  def show
  end
  private
  def set_item
    @item = Item.find(params[:id])
  end
end

src/app/views/admin/invitations/edit.html.erb
<%= form_with model: @invitation, url: admin_update_invitation_path do |f| %>
  <%= render 'shared/invitation_error_messages' %>
  <%= f.label :deleted, 'deleted' %>
  <%= f.select :deleted, [['F',false],['T',true]] %>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :name, class: 'text-field-field', placeholder: '名前' %>
    <%= f.label :name, '名前', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :account_id, class: 'text-field-field', placeholder: 'account_id' %>
    <%= f.label :account_id, 'account_id', class: 'text-field-label' %>
  </div>
  <br/>
  <div class="text-field-group">
    <%= f.text_field :invitation_code, class: 'text-field-field', placeholder: 'invitation_code' %>
    <%= f.label :invitation_code, 'invitation_code', class: 'text-field-label' %>
  </div>
  <br/>
  <%= f.label :uses, 'uses' %>
  <%= f.number_field :uses %>
  <br/>
  <%= f.label :max_uses, 'max_uses' %>
  <%= f.number_field :max_uses %>
  <br/>
  <%= f.label :expires_at, 'expires_at' %>
  <%= f.datetime_field :expires_at %>
  <br/>
  <%= f.submit '更新' %>
<% end %>

src/app/views/admin/invitations/index.html.erb
<% provide(:title, '招待たち') %>
<h1>招待たち</h1>
<div style="overflow-y:scroll;">
  <table>
    <tr>
      <th>ID</th>
      <th>詳細</th>
      <th>account_id</th>
      <th>name</th>
      <th>invitation_code</th>
      <th>uses</th>
      <th>max_uses</th>
      <th>expires_at</th>
      <th>deleted</th>
      <th>created_at</th>
      <th>updated_at</th>
    </tr>
    <% @invitations.each do |i| %>
      <tr>
        <td><%= i.id %></td>
        <td><%= link_to '詳細', admin_invitation_path(i.invitation_code) %></td>
        <td><%= i.account_id %></td>
        <td><%= i.name %></td>
        <td><%= i.invitation_code %></td>
        <td><%= i.uses %></td>
        <td><%= i.max_uses %></td>
        <td><%= i.expires_at %></td>
        <td><%= i.deleted %></td>
        <td><%= i.created_at %></td>
        <td><%= i.updated_at %></td>
      </tr>
    <% end %>
  </table>
</div>

src/app/views/admin/invitations/show.html.erb
<% provide(:title, '招待') %>
<h1>招待</h1>
<div style="overflow-y:scroll;">
  <table>
    <tr>
      <th>ID</th>
      <th>更新</th>
      <th>account_id</th>
      <th>name</th>
      <th>invitation_code</th>
      <th>uses</th>
      <th>max_uses</th>
      <th>expires_at</th>
      <th>deleted</th>
      <th>created_at</th>
      <th>updated_at</th>
    </tr>
    <tr>
      <td><%= @invitation.id %></td>
      <td><%= link_to '更新', admin_edit_invitation_path(@invitation.invitation_code) %></td>
      <td><%= @invitation.account_id %></td>
      <td><%= @invitation.name %></td>
      <td><%= @invitation.invitation_code %></td>
      <td><%= @invitation.uses %></td>
      <td><%= @invitation.max_uses %></td>
      <td><%= @invitation.expires_at %></td>
      <td><%= @invitation.deleted %></td>
      <td><%= @invitation.created_at %></td>
      <td><%= @invitation.updated_at %></td>
    </tr>
  </table>
</div>