src/config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  #sidekiq
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
  end

  # action cable
  mount ActionCable.server => '/cable'

  root 'timelines#index'
  
  # discovery
  get 'discovery' => 'discovery#index'

  # dashboard
  get 'dashboard' => 'dashboard#index'

  # timeline
  get 'tl' => 'timelines#tl'
  get 'tl/follow' => 'timelines#follow'
  get 'tl/current' => 'timelines#current'
  get 'tl/group/:group_aid' => 'timelines#group'

  # account
  get '@:name_id' => 'accounts#show', as: 'account', constraints: { name_id: /[A-Za-z0-9\-_\.@]*/ }
  get '@:name_id/icon' => 'accounts#show_icon', as: 'show_icon', constraints: { name_id: /.*/ }
  get '@:name_id/banner' => 'accounts#show_banner', as: 'show_banner', constraints: { name_id: /.*/ }
  post '@:name_id/follow' => 'accounts#follow', as: 'follow', constraints: { name_id: /.*/ }
  patch '@:name_id/upate' => 'accounts#update', as: 'update_account'

  # item
  get 'items' => 'items#index'
  get 'items/new' => 'items#new', as: 'new_item'
  post 'items/create' => 'items#create', as: 'create_item'
  get 'items/:aid' => 'items#show', as: 'item'
  get 'items/:aid/edit' => 'items#edit', as: 'edit_item'
  patch 'items/:aid/update' => 'items#update', as: 'update_item'
  delete 'items/:aid/destroy' => 'items#destroy', as: 'destroy_item'

  # reaction
  post 'react/:item_id/:emoji_id' => 'reactions#react', as: 'react'

  # storage
  get 'storage' => 'storage#index'

  # image
  resources :images, param: :aid, only: %i[ show create update delete ]
  get 'images/:aid/icon' => 'images#show_icon'
  get 'images/:aid/banner' => 'images#show_banner'

  # video
  resources :videos, param: :aid, only: %i[ create update delete ]

  # notifications
  #resources :videos, param: :aid, only: %i[ create update delete ]
  get 'notifications' => 'notifications#index'
  get 'notifications/new' => 'notifications#new', as: 'new_notification'
  post 'notifications/create' => 'notifications#create', as: 'create_notification'

  # message
  get 'messages' => 'messages#index'
  get 'messages/:group_aid' => 'messages#show', as: 'message'
  post 'message/:group_aid/create' => 'messages#create', as: 'create_message'

  # group
  get 'groups' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/create' => 'groups#create', as: 'create_group'
  get 'groups/:aid' => 'groups#show', as: 'group'
  post 'groups/:group_aid/add/:account_aid' => 'groups#group_add', as: 'group_add'
  post 'groups/:group_aid/remove/:account_aid' => 'groups#group_remove', as: 'group_remove'

  # emoji
  get 'emojis' => 'emojis#index'
  get 'emojis/new' => 'emojis#new', as: 'new_emoji'
  post 'emojis/create' => 'emojis#create', as: 'create_emoji'
  get 'emojis/:aid' => 'emojis#show', as: 'emoji'
  get 'emojis/:aid/edit' => 'emojis#edit', as: 'edit_emoji'
  patch 'emojis/:aid/update' => 'emojis#update', as: 'update_emoji'
  delete 'emojis/:aid/destroy' => 'emojis#destroy', as: 'destroy_emoji'

  # tag
  get 'tags' => 'tags#index'
  get 'tags/new' => 'tags#new', as: 'new_tag'
  post 'tags/create' => 'tags#create', as: 'create_tag'
  get 'tags/:aid' => 'tags#show', as: 'tag'
  get 'tags/:aid/edit' => 'tags#edit', as: 'edit_tag'
  patch 'tags/:aid/update' => 'tags#update', as: 'update_tag'
  delete 'tags/:aid/destroy' => 'tags#destroy', as: 'destroy_tag'

  # list

  # wallet

  # a_shop

  # product

  # map

  # world

  # application

  # subscription

  # signup
  get 'signup' => 'signup#index'
  get 'signup/check' => 'signup#check'
  post 'signup/entry' => 'signup#entry'
  post 'signup/create' => 'signup#create'

  # session
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#logout'

  # setting
  get 'settings' => 'settings#index'
  get 'settings/profile' => 'settings#profile'
  get 'settings/account' => 'settings#account'
  get 'settings/storage' => 'settings#storage'
  get 'settings/contents' => 'settings#contents'
  get 'settings/activity' => 'settings#activity'
  get 'settings/notifications' => 'settings#notifications'
  get 'settings/display' => 'settings#display'
  get 'settings/security_and_authority' => 'settings#security_and_authority'
  get 'settings/analytics' => 'settings#analytics'
  get 'settings/bills_and_payments' => 'settings#bills_and_payments'
  get 'settings/others' => 'settings#others'

  # resource
  get 'resources' => 'resources#index'
  get 'about' => 'resources#about'
  get 'info' => 'resources#info'
  get 'help' => 'resources#help'
  get 'privacy_policy' => 'resources#privacy_policy'
  get 'disclaimer' => 'resources#disclaimer'
  get 'page1' => 'resources#page1'
  get 'sitemap' => 'resources#sitemap'
  get 'tos' => 'resources#tos'
  get 'feedback' => 'resources#feedback'
  get 'help' => 'resources#help'
  get 'release_notes' => 'resources#release_notes'
  get 'blog' => 'resources#blog'

  # administorator
  namespace :admin do

    # dashboard
    root 'dashboard#index'

    # account
    resources :accounts, param: :aid, constraints: { name_id: /.*/ }, except: %i[ show ]

    # session
    resources :sessions, param: :uuid, except: %i[ show ]

    # invitation
    resources :invitations, param: :uuid, except: %i[ show ]

    # item
    get 'items' => 'items#index', as: 'items'

    # test
    get 'test' => 'test#index'
    get 'test/explore' => 'test#explore'
    get 'test/explore/:id' => 'test#show', constraints: { id: /.*/ }
    get 'test/new'
    post 'test/generate'
    post 'test/verify'
    post 'test/digest'
  end

  # api v1
  namespace :v1 do

    # app_status
    root 'resources#index'

    # session
    post 'sessions/new' => 'sessions#new'
    post 'sessions/check' => 'sessions#check'
    post 'login' => 'sessions#login'
    delete 'logout' => 'sessions#logout'

    # timeline
    post 'tl' => 'timelines#index'
    post 'tl/follow' => 'timelines#follow'#
    post 'tl/current' => 'timelines#current'#
    post 'tl/group/:group_aid' => 'timelines#group'#

    # account
    post '@:name_id' => 'accounts#show', as: 'account'
    post '@:name_id/followers' => 'accounts#followers', as: 'followers'
    post '@:name_id/following' => 'accounts#following', as: 'following'

    # signup
    post 'signup/check' => 'signup#check'
    post 'signup/create' => 'signup#create'

    # item
    post 'items' => 'items#index', as: 'items'
    post 'items/create' => 'items#create', as: 'create_items'
    post 'items/:item_id' => 'items#show', as: 'item'

    # activity pub
    post 'activitypub/inbox' => 'activity_pub#inbox'
  end

  # activity pub
  namespace :ap do
    # account
    get '@:name_id' => 'accounts#show', as: 'account'
    post '@:name_id/inbox' => 'accounts#inbox', as: 'account_inbox'
    get '@:name_id/outbox' => 'accounts#outbox', as: 'account_outbox'
    get '@:name_id/followers' => 'accounts#followers', as: 'account_followers'
    get '@:name_id/following' => 'accounts#following', as: 'account_following'
  end

  # .well-known
  get '/.well-known/host-meta' => 'well_known#host_meta'
  get '/.well-known/webfinger' => 'well_known#webfinger'

end

src/app/controllers/api/signup_controller.rb
class Api::SignupController < Api::ApplicationController
  before_action :logged_out_account, only: %i[check_invitation_code create]
  def check_invitation_code
    if Invitation.exists?(invitation_code: params[:invitation_code])
      render json: { invitation_code: true }
    else
      render json: { invitation_code: false }
    end
  end
  def create
    @account = Account.new(
      name: params[:name],
      name_id: params[:name_id],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if Invitation.exists?(invitation_code: params[:invitation_code])
      @account.account_id = unique_random_id(Account, 'account_id')
      account_icon_banner_attach('api')
      if @account.save
        render json: { created: true }
      else
        render json: { created: false }
      end
    else
      render json: { invitation_code: false }
    end
  end
  private
  def account_params
    params.require(:account).permit(:name, :name_id, :bio, :location, :birthday, :password, :password_confirmation)
  end
end

src/app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :logged_out_account, only: %i[check new create create_admin]
  def index
  end
  def check # 招待コードの入力
    if Account.first.blank?
      @account = Account.new
      render 'entry'
    end
  end
  def entry # アカウント情報の入力
    if Account.first.blank?
      @account = Account.new
    else
      invitation = check_invitation_code(params[:code])
      if invitation
        session[:code] = params[:code]
        @account = Account.new
      else
        render 'check'
      end
    end
  end
  def create
    @account = Account.new(account_params)
    if Account.first.blank?
      @account.activated = true
      @account.roles = ['administrator'].to_json
    else
      invitation = check_invitation_code(session[:code])
      unless invitation
        render 'entry'
        return
      end
    end
    @account.aid = unique_random_id(Account, 'aid')
    @account.activitypub_id = URI.join(ENV['APP_HOST'], '@' + params[:account][:name_id])
    key_pair = generate_rsa_key_pair
    @account.private_key = key_pair[:private_key]
    @account.public_key = key_pair[:public_key]
    if @account.save
      if invitation
        invitation.update(uses: invitation.uses + 1)
        session[:code].clear
      end
      flash[:success] = "アカウントが作成されました"
      redirect_to login_path
    else
      flash.now[:danger] = "間違っています。"
      render 'entry'
    end
  end
  private
  def account_params
    params.require(:account).permit(
      :name,
      :name_id,
      :summary,
      :location,
      :birthday,
      :password,
      :password_confirmation
    )
  end
  def check_invitation_code(code)
    invitation = Invitation.find_by(code: code)
    if !invitation
      flash.now[:danger] = "招待コードが無効です"
      return false
    elsif invitation.uses >= invitation.max_uses
      flash.now[:danger] = "招待コードの使用回数が上限に達しています"
      return false
    elsif invitation.deleted
      flash.now[:danger] = "削除された招待コードです"
      return false
    else
      flash[:success] = "有効な招待コードです"
      return invitation
    end
  end
end

src/app/controllers/v1/signup_controller.rb
class V1::SignupController < V1::ApplicationController
  before_action :logged_out_account, only: %i[ check create ]
  def check
    render json: { valid: Invitation.exists?(code: params[:code]) }
  end
  def create
    @account = Account.new(
      name: params[:name],
      name_id: params[:name_id],
      activitypub_id: URI.join(ENV['APP_HOST'], '@' + params[:name_id]),
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if Invitation.exists?(code: params[:code])
      @account.aid = unique_random_id(Account, 'aid')
      if @account.save
        render json: { status: 'created' }
      else
        render json: {
          status: 'rollbacked',
          message: @account.errors.full_messages.join(", ")
        }
      end
    else
      render json: { status: 'invalid_code' }
    end
  end
  private
  def account_params
    params.require(:account).permit(
      :name,
      :name_id,
      :summary,
      :location,
      :birthday,
      :password,
      :password_confirmation
    )
  end
end

src/app/views/signup/check.html.erb
<% provide(:layout_type, 'header_text') %>
<% provide(:header_text, 'サインアップ') %>
<% provide(:title, 'サインアップ') %>

<%= form_with url: signup_entry_path, data: { turbo: false } do |f| %>
  <%= f.text_field :code, class: '' %>
  <%= f.label :code, '招待コード', class: '' %>
  <%= f.submit '次へ' %>
<% end %>

src/app/views/signup/create.html.erb
<% provide(:title, 'サインアップ') %>
<% provide(:main_header_text, 'サインアップ') %>
<% content_for :main_content do %>
  <div class="signup-p3-container">
    <h1>おめでとうございます！</h1>
    <h2>アカウントが作成されました。</h2>
    <p>アカウントがアクティベートされたことを確認の上、ログインしてみましょう！</p>
  </div>
<% end %>
<%= render 'layouts/default' %>

src/app/views/signup/entry.html.erb
<% provide(:layout_type, 'header_text') %>
<% provide(:header_text, 'サインアップ') %>
<% provide(:title, 'サインアップ') %>

<%= form_with model: @account, url: signup_create_path, data: { turbo: false } do |f| %>
  <%= render 'shared/error_messages', instead: @account %>
  <%= f.label :name, '名前', class: '' %>
  <%= f.text_field :name, class: '' %>
  <br />
  <%= f.label :name_id, '表示ID', class: '' %>
  <%= f.text_field :name_id, class: '' %>
  <br />
  <%= f.label :summary, 'アカウント紹介文', class: '' %>
  <%= f.text_area :summary, class: '' %>
  <br />
  <%= f.label :location, '場所', class: '' %>
  <%= f.text_field :location, class: '' %>
  <br />
  <%= f.label :birthday, '誕生日' %>
  <%= f.datetime_field :birthday %>
  <br />
  <%= f.label :password, 'パスワード', class: '' %>
  <%= f.password_field :password, class: '' %>
  <br />
  <%= f.label :password_confirmation, 'パスワード確認', class: '' %>
  <%= f.password_field :password_confirmation, class: '' %>
  <br />
  <%= f.submit '作成' %>
<% end %>

src/app/views/signup/index.html.erb
<% provide(:layout_type, 'header_text') %>
<% provide(:header_text, 'サインアップ') %>
<% provide(:title, 'サインアップ') %>

<div class="">
  <h1>参加しよう</h1>
  <%= link_to 'はじめる', signup_check_path %>
</div>

src/app/views/signup/p1.html.erb
<% provide(:title, 'サインアップ') %>
<% provide(:main_header_text, 'サインアップ') %>
<% content_for :main_content do %>
  <div class="signup-p1-container">
    <%= form_with url: signup_profile_path, data: { turbo: false } do |f| %>
      <div class="text-field-group">
        <%= f.text_field :invitation_code, class: 'text-field-field', placeholder: '招待コード' %>
        <%= f.label :invitation_code, '招待コード', class: 'text-field-label' %>
      </div>
      <%= f.submit "次へ" %>
    <% end %>
  </div>
<% end %>
<%= render 'layouts/default' %>

src/app/views/signup/p2.html.erb
<% provide(:url, signup_create_path) %>
<% provide(:type, 'new') %>
<% provide(:submit_button_text, '作成') %>
<% provide(:title, 'サインアップ') %>
<% provide(:main_header_text, 'サインアップ') %>
<% content_for :main_content do %>
  <div class="signup-p2-container">
    <%= render 'shared/account_form' %>
  </div>
<% end %>
<%= render 'layouts/default' %>

src/app/views/signup/p3.html.erb
<% provide(:title, 'サインアップ') %>
<% provide(:main_header_text, 'サインアップ') %>
<% content_for :main_content do %>
  <div class="signup-p3-container">
    <h1>おめでとうございます！</h1>
    <h2>アカウントが作成されました。</h2>
    <p>アカウントがアクティベートされたことを確認の上、ログインしてみましょう！</p>
  </div>
<% end %>
<%= render 'layouts/default' %>